# typed: true
# frozen_string_literal: true

# This file was generated by Brewtap. DO NOT EDIT.
class TestGenerateFormulaEmptyFields < Formula
  desc "NA"
  homepage "https://github.com/m-dzianishchyts/test-generate-formula-empty-fields"
  url "https://github.com/m-dzianishchyts/test-generate-formula-empty-fields/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  def install
    bin.install "src/secure-browser-kiosk.sh" => "secure-browser-kiosk"
    ohai "Installed successfully."
  end
end
